### ISSUE TITLE
Images getting added to wrong directory

### ISSUE THREAD

**Issue by astrofrog** [dotastro/hack-list#41]
In https://github.com/dotastro/hack-list/pull/38, you can see that the image got added to ``8`` instead of ``dotastro8``

cc @eteq

**Comment by eteq** [comment]
@astrofrog - This is fixed by dotastro/hack-list-submission-app@1710b3ed771321805874d10833a44d329f3b7ce3 , along with (sort of) #60, which renders them correctly on the static output page
